// <auto-generated />
namespace BandAide.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modified_needBandQueryModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modified_needBandQueryModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201509141647498_modified_needBandQueryModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
