// <auto-generated />
namespace BandAide.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_Instrument_and_instrument_skill_models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Instrument_and_instrument_skill_models));
        
        string IMigrationMetadata.Id
        {
            get { return "201509020258594_added_Instrument_and_instrument_skill_models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
