// <auto-generated />
namespace BandAide.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class allowed_for_multiple_band_admins : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(allowed_for_multiple_band_admins));
        
        string IMigrationMetadata.Id
        {
            get { return "201509040123009_allowed_for_multiple_band_admins"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
