// <auto-generated />
namespace BandAide.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class many_2_many_2_1_2_many_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(many_2_many_2_1_2_many_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201509020533387_many_2_many_2_1_2_many_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
