// <auto-generated />
namespace BandAide.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_creator_prop_to_band : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_creator_prop_to_band));
        
        string IMigrationMetadata.Id
        {
            get { return "201509022235295_Added_creator_prop_to_band"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
