// <auto-generated />
namespace BandAide.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixed_many_to_many_with_owner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixed_many_to_many_with_owner));
        
        string IMigrationMetadata.Id
        {
            get { return "201509031435133_fixed_many_to_many_with_owner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
